using UnityEngine;
using System.Collections;
using UnityEditor;

namespace Tiled4Unity
{
    public class Tile4UnitySettings : ScriptableObject
    {

        private const string PathToSettings = "Assets/Tile4UnitySettings.asset";
        [Tooltip("Object type XML file generated by Tiled")] public TextAsset ObjectTypes;

        [MenuItem("Tiled4Unity/Settings")]
        public static void CreateSettings()
        {
            Tile4UnitySettings asset = GetSettings();

            EditorUtility.FocusProjectWindow();

            Selection.activeObject = asset;
        }

        public static Tile4UnitySettings GetSettings()
        {
            Tile4UnitySettings asset = AssetDatabase.LoadAssetAtPath<Tile4UnitySettings>(PathToSettings);

            if (asset == null)
            {
                asset = ScriptableObject.CreateInstance<Tile4UnitySettings>();
                AssetDatabase.CreateAsset(asset, PathToSettings);
                AssetDatabase.SaveAssets();
            }

            return asset;
        }
    }
}
