using UnityEngine;
using System.Collections;
using UnityEditor;

public class Tile4UnitySettings : ScriptableObject {

    private const string _pathToSettings = "Assets/Tile4UnitySettings.asset";
    [Tooltip("Object type XML file generated by Tiled")]
    public TextAsset ObjectTypes;

    [MenuItem("Tiled4Unity/Settings")]
    public static void CreateSettings()
    {
        Tile4UnitySettings asset = GetSettings();

        EditorUtility.FocusProjectWindow();

        Selection.activeObject = asset;
    }

    public static Tile4UnitySettings GetSettings()
    {
        Tile4UnitySettings asset = AssetDatabase.LoadAssetAtPath<Tile4UnitySettings>(_pathToSettings);

        if (asset == null)
        {
            asset = ScriptableObject.CreateInstance<Tile4UnitySettings>();
            AssetDatabase.CreateAsset(asset, _pathToSettings);
            AssetDatabase.SaveAssets();
        }

        return asset;
    }
}
